### ISSUE TITLE
Does not work in Android browser

### ISSUE THREAD

**Issue by AdvancedStyle** [andrastoth/WebCodeCam#4]
When clicking play button in Android it does nothing (does not open camera).

Android browser version 4.2.2-20141113.214651

(This is based on the demo page: http://atandrastoth.co.uk/main/pages/plugins/codereader/ )

**Comment by andrastoth** [comment]
Hi,
I don't understand, because on my mobile working correctly. 
(ZTE Blade V Android v4.1.2 with facing-Environment)
Try Chrome browser newest version.
But I think on Android best solution a Native app, because browser auto focus not working.
I wrote myself an application, using ZXing source, for bar code decoding.

**Comment by AdvancedStyle** [comment]
(All below tests on Android)
In the standard Android "Browser" app no camera appears.
In Chrome the camera shares, but just shows a green gradient (no picture visible)
In Firefox the camera works and has picture, but the read recognition is a lot lower than on a desktop (have to tweek all the settings and move the camera around for 5 minutes before getting a scan).

**Comment by andrastoth** [comment]
Unfortunately, this problem is caused by the system and browser. 
Try another solution, but I think no one will be perfect to work. Maybe browser to a later version will solve the problem.
